<a href="https://colab.research.google.com/github/Jhamaal15/Machine_Learning/blob/main/Final_score_pred_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

df = pd.read_csv("student_performance_cleanedd.csv")

df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Study_Hours_Normalized,Gender_Encoded,Attendance_Normalized
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,0.041199,1,1.000000
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.194757,1,0.960000
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.194757,0,0.920000
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.093633,0,0.586667
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.116105,1,0.973333

In [13]:
X = df[["Attendance", "Study_Hours"]]

y = df["Final_Score"]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 80
Testing samples: 20

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

model

LinearRegression()

In [20]:
model.fit(X_train, y_train)

LinearRegression()

In [21]:
predictions = model.predict(X_test)

print(predictions)

[ 55.60987668  50.48876769  73.16796464  72.60971344  71.96467391
  86.11086739  64.0502166   71.5057984   58.0578088   45.94017113
 100.97522357  55.61700729  80.57080056  55.94959527  63.3186296
  53.60187578  55.71680145  81.38875741  61.87541444  69.68336544]

In [22]:
comparison = pd.DataFrame({
    "Actual Score": y_test.values,
    "Predicted Score": predictions
})

comparison

    Actual Score  Predicted Score
0           42.2        55.609877
1           57.8        50.488768
2           75.4        73.167965
3           72.4        72.609713
4           77.6        71.964674
5           86.0        86.110867
6           75.6        64.050217
7           67.6        71.505798
8           59.8        58.057809
9           43.0        45.940171
10         100.0       100.975224
11          62.2        55.617007
12          81.4        80.570801
13          50.0        55.949595
14          62.0        63.318630
15          53.4        53.601876
16          53.6        55.716801
17          74.6        81.388757
18          69.4        61.875414
19          66.0        69.683365

In [23]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, predictions)

print("Mean Squared Error:", mse)

Mean Squared Error: 31.665647494071862